### ISSUE TITLE
error building freecad-0.18.4

### ISSUE THREAD

**Issue by CaptainBloodz** [waebbl/waebbl-gentoo#187] opened 2020-02-04 14:39 UTC
```
emerge --info media-gfx/freecad::waebbl
FEATURES variable contains unknown value(s): distcc-pump
Portage 2.3.84 (python 3.6.9-final-0, default/linux/amd64/17.1, gcc-9.2.0, glibc-2.29-r7, 5.5.1-gentoo-classic x86_64)

                         System Settings
System uname: Linux-5.5.1-gentoo-classic-x86_64-Intel-R-_Core-TM-_i3-6100_CPU_@_3.70GHz-with-gentoo-2.6
KiB Mem:     3936884 total,   1389228 free
KiB Swap:    8048528 total,   7914384 free
Timestamp of repository waebbl: Tue, 28 Jan 2020 09:25:23 +0000
Head commit of repository waebbl: 30f2e3dfe9f756c82a0afbbb6475854eb69d23a4

Timestamp of repository gentoo: Tue, 04 Feb 2020 12:45:01 +0000
Head commit of repository gentoo: fea0e8134213d344e229f48c13171dfc24683bea

Timestamp of repository raiagent: Tue, 04 Feb 2020 02:46:39 +0000
Head commit of repository raiagent: adb230d1133f45f98b9244d3ff3e59a8eb4e9e02

sh bash 4.4_p23-r1
ld GNU ld (Gentoo 2.32 p2) 2.32.0
distcc 3.3.3 x86_64-pc-linux-gnu [disabled]
app-shells/bash:          4.4_p23-r1::gentoo
dev-java/java-config:     2.2.0-r4::gentoo
dev-lang/perl:            5.30.1::gentoo
dev-lang/python:          2.7.17::gentoo, 3.6.9::gentoo, 3.7.5-r1::gentoo
dev-util/cmake:           3.14.6::gentoo
dev-util/pkgconfig:       0.29.2::gentoo
sys-apps/baselayout:      2.6-r1::gentoo
sys-apps/openrc:          0.42.1::gentoo
sys-apps/sandbox:         2.13::gentoo
sys-devel/autoconf:       2.13-r1::gentoo, 2.69-r4::gentoo
sys-devel/automake:       1.16.1-r1::gentoo
sys-devel/binutils:       2.32-r1::gentoo
sys-devel/gcc:            9.2.0-r3::gentoo
sys-devel/gcc-config:     2.1::gentoo
sys-devel/libtool:        2.4.6-r6::gentoo
sys-devel/make:           4.2.1-r4::gentoo
sys-kernel/linux-headers: 4.19::gentoo (virtual/os-headers)
sys-libs/glibc:           2.29-r7::gentoo

ACCEPT_KEYWORDS="amd64"
ACCEPT_LICENSE="* -@EULA"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-march=skylake -mtune=skylake  -O2             -pipe"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/php/apache2-php7.3/ext-active/ /etc/php/cgi-php7.3/ext-active/ /etc/php/cli-php7.3/ext-active/ /etc/revdep-rebuild /etc/sandbox.d /etc/splash /etc/terminfo /etc/texmf/language.dat.d /etc/texmf/language.def.d /etc/texmf/updmap.d /etc/texmf/web2c"
CXXFLAGS="-march=skylake -mtune=skylake  -O2             -pipe    "
DISTDIR="/var/cache/distfiles"
EMERGE_DEFAULT_OPTS="--alert y 			--alphabetical 			--ask-enter-invalid 			--autounmask y  			--autounmask-only n  			--autounmask-unrestricted-atoms y  			--autounmask-write y 			--misspell-suggestions n 			--noconfmem 			--nospinner   			--tree 			--with-bdeps y"
ENV_UNSET="DBUS_SESSION_BUS_ADDRESS DISPLAY GOBIN PERL5LIB PERL5OPT PERLPREFIX PERL_CORE PERL_MB_OPT PERL_MM_OPT XAUTHORITY XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME XDG_RUNTIME_DIR"
FCFLAGS="-march=skylake -mtune=skylake  -O2             -pipe"
FEATURES="assume-digests binpkg-docompress binpkg-dostrip binpkg-logs config-protect-if-modified distcc-pump distlocks ebuild-locks fixlafiles ipc-sandbox merge-sync multilib-strict network-sandbox news parallel-fetch pid-sandbox preserve-libs protect-owned sandbox sfperms split-elog strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync"
FFLAGS="-march=skylake -mtune=skylake  -O2             -pipe"
GENTOO_MIRRORS="http://ftp.free.fr/mirrors/ftp.gentoo.org/ https://mirrors.evowise.com/gentoo/ http://mirror.dkm.cz/gentoo/ http://mirror.eu.oneandone.net/linux/distributions/gentoo/gentoo/ http://mirror.netcologne.de/gentoo/ http://mirror.leaseweb.com/gentoo/ http://mirror.bytemark.co.uk/gentoo/ http://gentoo.mirror.web4u.cz/ http://linux.rz.ruhr-uni-bochum.de/download/gentoo-mirror/"
LANG="fr_FR.utf8"
LDFLAGS="  -Wl,-O1       -Wl,-fuse-ld=bfd  -Wl,--enable-new-dtags  -march=skylake -mtune=skylake  -O2             -pipe "
LINGUAS="fr"
MAKEOPTS="-j3 -l3"
PKGDIR="/var/cache/binpkgs"
PORTAGE_COMPRESS="lzma"
PORTAGE_COMPRESS_FLAGS="-9"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/var/tmp"
USE="amd64 asm minimal split-usr" ABI_X86="64" ALSA_CARDS="hda-intel" CPU_FLAGS_X86="aes avx avx2 f16c fma3 mmx mmxext pclmul popcnt sse sse2 sse3 sse4_1 sse4_2 ssse3" ELIBC="glibc" GRUB_PLATFORMS="pc" INPUT_DEVICES="libinput" KERNEL="linux" L10N="fr" PHP_TARGETS="php7-3" PYTHON_SINGLE_TARGET="python3_7" PYTHON_TARGETS="python2_7 python3_6 python3_7" QEMU_USER_TARGETS="aarch64" RUBY_TARGETS="ruby25" USERLAND="GNU" VIDEO_CARDS="intel i965"
Unset:  CC, CPPFLAGS, CTARGET, CXX, INSTALL_MASK, LC_ALL, PORTAGE_BINHOST, PORTAGE_BUNZIP2_COMMAND, PORTAGE_RSYNC_EXTRA_OPTS
```
--
```
eix pyside
[I] dev-python/pyside2 [2]
     Installed versions:  5.12.5-r3^t(17:11:17 04/02/2020)(gui svg widgets -3d -charts -concurrent -datavis -designer -gles2 -help -location -multimedia -network -positioning -printsupport -qml -quick -script -scripttools -scxml -sensors -speech -sql -test -testlib -webchannel -webengine -websockets -x11extras -xml -xmlpatterns PYTHON_TARGETS="python3_6 -python2_7 -python3_7")
     Homepage:            https://wiki.qt.io/PySide2
     Description:         Python bindings for the Qt framework

[I] dev-python/pyside2-tools [2]
     Installed versions:  5.12.5-r1^t(17:11:52 04/02/2020)(-test PYTHON_TARGETS="python3_6 -python2_7 -python3_7")
     Homepage:            https://wiki.qt.io/PySide2
     Description:         PySide development tools (lupdate, rcc, uic)
```
--
```
[media-gfx:freecad-0.18.4:20200209-083833.log.zip](https://github.com/waebbl/waebbl-gentoo/files/4176622/media-gfx.freecad-0.18.4.20200209-083833.log.zip)
```

Edit (waebbl): edited formatting

**Comment by waebbl** [comment] 2020-02-04 18:15
Thanks for the report @CaptainBloodz. The log snippet you posted unfortunately does not contain any error message, only warning and note message.
Could you eventually please post the complete build log on some pasting website and post the link to it here?

**Comment by CaptainBloodz** [comment] 2020-02-05 10:55
Sure I will, be it will take some time, not too long, as ebuild log have been deleted, thus requiring a whole stack rebuild. Sorry for the dirty display above. Will do my best to update the post along with a better looking.
Thks 4 ur attention, interest & support.

**Comment by waebbl** [comment] 2020-02-05 18:17
The display's not a problem ;) My markdown skills are not good enough to find the reason for this display, tried it, but with no success.

**Comment by CaptainBloodz** [comment] 2020-02-09 08:53
Same issue, likely:[https://forums.gentoo.org/viewtopic-t-1108062-highlight-.html](url)

**Comment by waebbl** [comment] 2020-02-09 13:11
For some reason, I couldn't post on the forums... O.o
Assuming, you're having the same bug, which versions of qtcore, qtchooser and pyside do you use?

Rcc from qtchooser-66 and qtcore-5.14.1 (contains the acutal binary `/usr/lib64/qt5/bin/rcc`) does know about the `-g` option and works well with pyside2-tools-5.14.1::raiagent[-tools] here.

**Comment by CaptainBloodz** [comment] 2020-02-09 17:55
eix qtcore
Installed versions:  5.13.2-r2(5/5.13)^t(13:26:32 04/02/2020)(icu -debug -systemd -test)
--
eix qtchooser
Installed versions:  66(23:06:47 04/11/2019)(-test)
--
emerge -p pyside2-tools
[ebuild  N    ~] dev-python/pyside2-tools-5.12.5-r1  USE="-test" PYTHON_TARGETS="-python2_7 python3_6 -python3_7" 
[ebuild  N    ~]  dev-python/pyside2-5.12.5-r3  USE="-3d -charts -concurrent -datavis -designer -gles2 gui -help -location -multimedia -network -positioning -printsupport -qml -quick -script -scripttools -scxml -sensors -speech -sql svg -test -testlib -webchannel -webengine -websockets widgets -x11extras -xml -xmlpatterns" PYTHON_TARGETS="-python2_7 python3_6 -python3_7" 
[ebuild  N    ~]   dev-python/shiboken2-5.12.5-r3  USE="-docstrings -numpy -test" PYTHON_TARGETS="-python2_7 python3_6 -python3_7"

**Comment by waebbl** [comment] 2020-02-09 21:18
Qtchooser only provides the link, the actual binary belongs to qtcore.

Ok, so this issue is related to https://github.com/waebbl/waebbl-gentoo/blob/master/media-gfx/freecad/files/freecad-0.18.4-0003-cMake-FindPySide2Tools.cmake-use-generator-option.patch which uses the new option from qt-5.14.
Unfortunately the freecad ebuild depends only on pyside2 without any version.

I'm going to fix this. Will take a few days though.

**Comment by nick87720z** [comment] 2020-02-12 10:11
@CaptainBloodz  When editing at github webui, pressing "insert code" with selected (pasted) code should do the work. Besides that, when it comes to desktop markdown edit, I use quilter (may need packaging, at least I have it in personal).

**Comment by waebbl** [comment] 2020-02-23 20:55
This is a duplicate of issue #194 
I'm closing this in favor of the other issue, which refers to the current version.

**Closed by waebbl** 2020-02-23 20:55 UTC
Labels: bug, duplicate
