### ISSUE TITLE
Boost placeholder problem while compiling freecad

### ISSUE THREAD

**Issue by sergeyglazyrindev** [waebbl/waebbl-gentoo#235] opened 2020-05-15 23:48 UTC
Problem with placeholder replacement during compilation in GroupExtension.cpp.o
```
FAILED: src/App/CMakeFiles/FreeCADApp.dir/GroupExtension.cpp.o
/usr/bin/x86_64-pc-linux-gnu-g++ -DBOOST_107300 -DDOCDIR=\"/usr/share/doc/freecad-99991\" -DFreeCADApp_EXPORTS -DHAVE_CONFIG_H -DQT_CORE_LIB -DQT_NO_DEBUG -DQT_XML_LIB -DRESOURCEDIR=\"/usr/share/freecad/data\" -D_OCC64 -I. -Isrc -I/var/tmp/portage/media-gfx/freecad-99991/work/freecad-99991/src -Isrc/App -I/usr/include/python3.6m -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++ -isystem /usr/include/qt5/QtXml  -Wall -Wextra -Wno-write-strings -march=native -O2 -pipe -fPIC   -fPIC -std=gnu++11 -MD -MT src/App/CMakeFiles/FreeCADApp.dir/GroupExtension.cpp.o -MF src/App/CMakeFiles/FreeCADApp.dir/GroupExtension.cpp.o.d -o src/App/CMakeFiles/FreeCADApp.dir/GroupExtension.cpp.o -c /var/tmp/portage/media-gfx/freecad-99991/work/freecad-99991/src/App/GroupExtension.cpp
/var/tmp/portage/media-gfx/freecad-99991/work/freecad-99991/src/App/GroupExtension.cpp: In member function ‘virtual void App::GroupExtension::extensionOnChanged(const App::Property*)’:
[b]/var/tmp/portage/media-gfx/freecad-99991/work/freecad-99991/src/App/GroupExtension.cpp:364:68: error: ‘_1’ was not declared in this scope[/b]
  364 |                             &GroupExtension::slotChildChanged,this,_1,_2));
```
Here is my build information:
https://pastebin.com/A3rGA6wg
Here is build log:
https://drive.google.com/file/d/1wA8sk8iXAal7loFAJw6FJEPJwgaExBgT/view?usp=sharing

Here is emerge --info:
```
Portage 2.3.99 (python 3.7.7-final-0, default/linux/amd64/17.1/desktop/plasma, gcc-10.1.0, glibc-2.31-r2, 5.6.2-gentoo x86_64)
=================================================================
                         System Settings
=================================================================
System uname: Linux-5.6.2-gentoo-x86_64-Intel-R-_Core-TM-_i5-4440_CPU_@_3.10GHz-with-gentoo-2.7
KiB Mem:    28660264 total,   5062260 free
KiB Swap:    2929660 total,   2928636 free
Timestamp of repository gentoo: Sat, 09 May 2020 22:30:01 +0000
Head commit of repository gentoo: 399366c2d7d102eba172f0a811255586c66a5131
Timestamp of repository poly-c: Sat, 04 Jan 2020 11:55:30 +0000
sh bash 4.4_p23-r1
ld GNU ld (Gentoo 2.34 p1) 2.34.0
app-shells/bash:          4.4_p23-r1::gentoo
dev-java/java-config:     2.2.0-r4::gentoo
dev-lang/perl:            5.30.2::gentoo
dev-lang/python:          2.7.18::gentoo, 3.5.9::gentoo, 3.6.10-r2::gentoo, 3.7.7-r2::gentoo, 3.8.2-r2::gentoo
dev-util/cmake:           3.17.2::gentoo
sys-apps/baselayout:      2.7::gentoo
sys-apps/openrc:          0.42.1::gentoo
sys-apps/sandbox:         2.18::gentoo
sys-devel/autoconf:       2.13-r1::gentoo, 2.69-r5::gentoo
sys-devel/automake:       1.13.4-r2::gentoo, 1.15.1-r2::gentoo, 1.16.2::gentoo
sys-devel/binutils:       2.34::gentoo
sys-devel/gcc:            4.4.7-r3::gentoo, 5.5.0::gentoo, 9.3.0::gentoo, 10.1.0::gentoo
sys-devel/gcc-config:     2.2.1::gentoo
sys-devel/libtool:        2.4.6-r6::gentoo
sys-devel/make:           4.3::gentoo
sys-kernel/linux-headers: 5.6::gentoo (virtual/os-headers)
sys-libs/glibc:           2.31-r2::gentoo
Repositories:

gentoo
    location: /var/db/repos/gentoo
    sync-type: rsync
    sync-uri: rsync://rsync.gentoo.org/gentoo-portage
    priority: -1000
    sync-rsync-verify-jobs: 1
    sync-rsync-extra-opts:
    sync-rsync-verify-max-age: 24
    sync-rsync-verify-metamanifest: yes

local
    location: /usr/local/portage/overlay
    masters: gentoo
    priority: 0

ArtSoftware
    location: /var/lib/layman/ArtSoftware
    masters: gentoo
    priority: 50

AstroFloyd
    location: /var/lib/layman/AstroFloyd
    masters: gentoo
    priority: 50

R_Overlay
    location: /var/lib/layman/R_Overlay
    masters: gentoo
    priority: 50

cg
    location: /var/lib/layman/cg
    masters: gentoo
    priority: 50

chrytoo
    location: /var/lib/layman/chrytoo
    masters: gentoo
    priority: 50

dotnet
    location: /var/lib/layman/dotnet
    masters: gentoo
    priority: 50

eclipse
    location: /var/lib/layman/eclipse
    masters: gentoo
    priority: 50

fordfrog
    location: /var/lib/layman/fordfrog
    masters: gentoo
    priority: 50

gamerlay
    location: /var/lib/layman/gamerlay
    masters: gentoo
    priority: 50

go-overlay
    location: /var/lib/layman/go-overlay
    masters: gentoo
    priority: 50

hering-overlay
    location: /var/lib/layman/hering-overlay
    masters: gentoo
    priority: 50

hossie
    location: /var/lib/layman/hossie
    masters: gentoo
    priority: 50

jorgicio
    location: /var/lib/layman/jorgicio
    masters: gentoo
    priority: 50

linxon
    location: /var/lib/layman/linxon
    masters: gentoo
    priority: 50

mva
    location: /var/lib/layman/mva
    masters: gentoo
    priority: 50

pf4public
    location: /var/lib/layman/pf4public
    masters: gentoo
    priority: 50

poly-c
    location: /var/lib/layman/poly-c
    masters: gentoo
    priority: 50

raiagent
    location: /var/lib/layman/raiagent
    masters: gentoo
    priority: 50

science
    location: /var/lib/layman/science
    masters: gentoo
    priority: 50

scrill
    location: /var/lib/layman/scrill
    masters: gentoo
    priority: 50

snapd
    location: /var/lib/layman/snapd
    masters: gentoo
    priority: 50

ssnb
    location: /var/lib/layman/ssnb
    masters: gentoo
    priority: 50

steam-overlay
    location: /var/lib/layman/steam-overlay
    masters: gentoo
    priority: 50

stefantalpalaru
    location: /var/lib/layman/stefantalpalaru
    masters: gentoo
    priority: 50

stuff
    location: /var/lib/layman/stuff
    masters: gentoo
    priority: 50

waebbl
    location: /var/lib/layman/waebbl
    masters: gentoo raiagent
    priority: 50

ACCEPT_KEYWORDS="amd64 ~amd64"
ACCEPT_LICENSE="* -@EULA"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-march=native -O2 -pipe"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/lib64/libreoffice/program/sofficerc /usr/share/config /usr/share/gnupg/qualified.txt /usr/share/sddm/scripts/Xsetup"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo"
CXXFLAGS="-march=native -O2 -pipe"
DISTDIR="/var/cache/distfiles"
ENV_UNSET="DBUS_SESSION_BUS_ADDRESS DISPLAY GOBIN PERL5LIB PERL5OPT PERLPREFIX PERL_CORE PERL_MB_OPT PERL_MM_OPT XAUTHORITY XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME XDG_RUNTIME_DIR"
FCFLAGS="-march=native -O2 -pipe"
FEATURES="assume-digests binpkg-docompress binpkg-dostrip binpkg-logs config-protect-if-modified distlocks ebuild-locks fixlafiles ipc-sandbox merge-sync multilib-strict network-sandbox news parallel-fetch preserve-libs protect-owned qa-unresolved-soname-deps sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-march=native -O2 -pipe"
GENTOO_MIRRORS="ftp://ftp.wh2.tu-dresden.de/pub/mirrors/gentoo"
LANG="en_US.utf8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
MAKEOPTS="-j4"
PKGDIR="/var/cache/binpkgs"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/var/tmp"
USE="X a52 aac acl acpi activities alsa amd64 berkdb bluetooth branding bzip2 cairo cdda cdr cli connection-sharing crypt cups dbus declarative dri dts dvd dvdr elogind emboss encode exif flac fortran gdbm gif iconv icu ipv6 jpeg kde kipi kwallet lcms ldap libnotify libtirpc lm_sensors mad mng mp3 mp4 mpeg mtp multilib ncurses networkmanager nls nptl ogg opengl openmp pam pango pcre pdf phonon plasma png policykit ppds pulseaudio qml qt5 readline scanner sdl seccomp semantic-desktop spell split-usr ssl startup-notification svg tahoma tcpd tiff truetype udev udisks unicode upower usb v4l vorbis widgets wifi wxwidgets x264 xattr xcb xcomposite xml xv xvid zlib" ABI_X86="64" ADA_TARGET="gnat_2018" ALSA_CARDS="ali5451 als4000 atiixp atiixp-modem bt87x ca0106 cmipci emu10k1x ens1370 ens1371 es1938 es1968 fm801 hda-intel intel8x0 intel8x0m maestro3 trident usb-audio via82xx via82xx-modem ymfpci" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="karbon sheets words" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="mmx mmxext sse sse2" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock greis isync itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf skytraq superstar2 timing tsip tripmate tnt ublox ubx" GRUB_PLATFORMS="efi-64" INPUT_DEVICES="synaptics evdev" KERNEL="linux" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php7-2" POSTGRES_TARGETS="postgres10 postgres11" PYTHON_SINGLE_TARGET="python3_7" PYTHON_TARGETS="python2_7 python3_7" RUBY_TARGETS="ruby24 ruby25" SANE_BACKENDS="hp" USERLAND="GNU" VIDEO_CARDS="amdgpu radeonsi radeon intel" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  CC, CPPFLAGS, CTARGET, CXX, EMERGE_DEFAULT_OPTS, INSTALL_MASK, LC_ALL, LINGUAS, PORTAGE_BINHOST, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS

```

I use my own freecad ebuild which is almost the same as yours, except:

1. added keyword "~amd64" for 9999 version, cause it doesn't work without keyword
2. commented dependency >=sci-libs/med-4.0.0-r1[mpi(+)?,python,${PYTHON_SINGLE_USEDEP}]
3.  because couldn't find 4.0.0 version of med for gentoo and compiled it manually for now, later on I want to create ebuild for it.
4. changed -DOCC_LIBRARY_DIR to "${CASROOT}/lib64", without it doesn't find opencascade so files, TKMath, etc...

**Comment by waebbl** [comment] 2020-05-16 07:23
Several issues with your report:
- The build log is protected, I can not view it.
- You don't need to add ~amd64, instead you need to unmask the freecad ebuild
- There are sci-libs/med-4.0.0-r{1,2} in the Gentoo tree, so no need to comment it.
- OCC has been reported already in issue #228, so this is likely to be a duplicate.

I'm closing this, as it's not an ebuild from this overlay. Feel free to re-open it, once you can reproduce a non-duplicate issue with the ebuild from my overlay. For duplicates, please use the already open issues for commenting.

If you want to use live ebuilds please think about this: It can fail one day and succeed the other day. This isn't necessarily due to errors in the ebuild. It's possible, upstream changed something, so the ebuild needs an update. But it's also possible there has been a bug introduced upstream with one of the commits, which get's fixed a bit later and you just happen to have pulled in the time this bug was there. So with live ebuilds always double check whether an issue is related to the ebuild or to an upstream bug.

**Closed by waebbl** 2020-05-16 07:23 UTC
