### ISSUE TITLE
sci-libs/vtk-8.2.0_rc1 build error

### ISSUE THREAD

**Issue by brothermechanic** [waebbl/waebbl-gentoo#86] opened 2019-04-29 11:35 UTC
/var/tmp/portage/sci-libs/vtk-8.2.0_rc1/work/vtk-8.2.0_rc1_build/ThirdParty/libproj/vtk_libproj.h fatal error: projects.h: No such file or directory
[build.log](https://github.com/waebbl/waebbl-gentoo/files/3127213/build.log)

**Comment by waebbl** [comment] 2019-05-06 05:00
This ebuild is from your overlay. Have you tried the 8.2.0 from overlay?
Invalid report, so closing it. Feel free to reopen it, if the issue consists with the ebuild from my overlay.

**Comment by brothermechanic** [comment] 2019-05-06 10:51
this is your ebuild + python 3.7
i need python 3.7 - this is blender hard dep
please add experimental ebuild with python 3.7
i think your ebuild has this issue anyway

**Comment by waebbl** [comment] 2019-05-06 16:24
No it's not my ebuild. My ebuild has
PYTHON_COMPAT=( python3_6 )
and is therefore not able to compile against python 3.7
The system isn't ready for python-3.7 else it would be stable already in the tree. I'm sorry, I can not fix this.

**Comment by brothermechanic** [comment] 2019-05-06 17:03
nice

**Comment by l29ah** [comment] 2019-06-05 22:56
I observe this problem with 8.2.0::waebbl.
python-3.6 here.

**Comment by waebbl** [comment] 2019-06-05 23:06
Please re-open an issue, when the issue pops up again!

Could you please provide the usual files for a bug report? 
Build log and output of emerge --info =vtk-8.2.0::waebbl
Thank you

**Comment by l29ah** [comment] 2019-06-06 01:27
Only the repo owner can reopen issues on github.

https://dump.bitcheese.net/files/cifuzyz/build.log
https://bpaste.net/show/06623330c640

**Comment by waebbl** [comment] 2019-06-11 10:53
Hmm, I can not reproduce this. It compiled just fine yesterday, even after switch to 17.1. Looking at the USE flags there seems also be no difference.
Could you please check which version of sci-libs/proj you have installed?

**Comment by l29ah** [comment] 2019-06-11 10:54
6.0.0::cg

**Comment by waebbl** [comment] 2019-06-11 11:31
I suppose that's the problem. I'm using stable 4.9.2.
Version 6.0.0 has been in portage main tree only for 3 weeks or so. I'm not sure, whether vtk already supports the 6.0.0 version.

**Comment by waebbl** [comment] 2019-06-11 11:37
Proj-6.0.0 has been released in march, while vtk-8.2.0 has been released in january. It's very unlikely vtk does already support the new proj.
I suggest sticking to the 4.9.2 release until vtk updates to something >8.2.0.

**Comment by waebbl** [comment] 2019-06-11 11:53
I just tested to update to proj-6.0.0. Of the revdep's on my machine, which are sci-libs/shapelib, dev-db/spatialite, sci-libs/libgeotiff, dev-db/postgis, sci-geosciences/qgis and sci-libs/vtk all fail due to issues for the updated proj version. The version does still have some issues in gentoo.

**Comment by l29ah** [comment] 2019-06-11 12:18
Yeah, downgrading proj worked, thank you.

**Comment by waebbl** [comment] 2019-06-11 15:53
So I'm closing this.

**Closed by waebbl** 2019-06-11 15:53 UTC
