### ISSUE TITLE
media-gfx/freecad-9999::waebbl opencascade library failure

### ISSUE THREAD

**Issue by kshots** [waebbl/waebbl-gentoo#56] opened 2019-01-16 18:47 UTC
Appears to fail to link properly when built on amd64 architectures. The below patch fixes the problem.

```
diff -Naur old/freecad-9999.ebuild new/freecad-9999.ebuild
--- old/freecad-9999.ebuild	2019-01-16 13:44:25.864371984 -0500
+++ new/freecad-9999.ebuild	2019-01-16 13:43:44.270189540 -0500
@@ -157,7 +157,7 @@
 		-DFREECAD_USE_PCL=$(usex pcl)
 		# opencascade-7.3.0 sets CASROOT in /etc/env.d/51opencascade
 		-DOCC_INCLUDE_DIR="${CASROOT}"/include/opencascade
-		-DOCC_LIBRARY_DIR="${CASROOT}"/$(get_libdir)
+		-DOCC_LIBRARY_DIR="${CASROOT}"/lib
 		-DOPENMPI_INCLUDE_DIRS=/usr/include/
 	)
 

```

Background:

It appears you're thinking that the $CASROOT lib dir differentiates between architectures. It does not. $CASROOT/lib64 does not exist.

On my system:

```
rich@graendal /tmp $ echo $CASROOT
/usr/lib64/opencascade-7.3.0/ros
rich@graendal /tmp $ ls $CASROOT
bin  include  lib  share
```

**Comment by kshots** [comment] 2019-01-17 18:33
> Hi @kshots thanks for pointing this out. Do you use 17.0 or 17.1 profile, and which opencascade? The one from the main tree, or the one from my overlay? On my system (17.0, occ from my overlay) `$CASROOT` has a `lib64` subdir. The ebuild in the main tree is based on an older version of the one in my overlay.
```

rich@graendal ~ $ eselect profile show
Current /etc/portage/make.profile symlink:
  default/linux/amd64/17.0/desktop/gnome/systemd
rich@graendal ~ $ emerge -pv opencascade

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild   R   ~] sci-libs/opencascade-7.3.0:7.3.0::waebbl  USE="ffmpeg freeimage gl2ps java qt5 tbb vtk -debug -doc -examples -gles2 -inspector -optimize -test" 47,439 KiB

Total: 1 package (1 reinstall), Size of downloads: 47,439 KiB
```
Odd... I'm using opencascade from your overlay, but not getting the lib64 folder you get.

**Comment by waebbl** [comment] 2019-01-18 15:14
> EDIT2: You're not losing your mind, I see the following in your ebuild that would cause what you're describing:
> 
> `sed -i -e 's|ros/lib|ros/'$(get_libdir)'|' "${T}/${PV}" || die`
> 
> Any chance you updated the ebuild without incrementing the revision? Maybe I need to rebuild opencascade...

It might very well be possible I forgot incrementing the revision. I'm still a little unsure on when to update revisions and there's a chance I'm not handling revision as strong yet as it should go.

I'll keep the issue open for reviewing when 17.1 becomes stable.

**Comment by Perlovka** [comment] 2020-01-23 23:43
There is one more problem, if sci-libs/oce is installed, FreeCAD will use it instead of opencascade.

**Comment by waebbl** [comment] 2020-01-24 06:26
IMO this would be an upstream issue. IIRC freecad does support both, but I will check again.

**Comment by nick87720z** [comment] 2020-02-01 11:09
I just retried opencascade:7.3.0::gentoo, and its okay.
But from this overlay it fails.

**Comment by waebbl** [comment] 2020-02-01 12:07
You don't need to use opencascade from this overlay. I'm also the proxy maintainer for the version in the Gentoo tree, so just stick to the versions there. The one's in my overlay will be removed soon.

**Comment by nick87720z** [comment] 2020-02-01 18:25
Btw, I was wrong. 
opencascade::gentoo can at least confiugre, but compilation fails with USE=tbb (did not try without).

**Comment by khumarahn** [comment] 2020-05-04 10:06
I am hitting this on 17.1 profile with opencascade-7.4.0-r2::gentoo, trying to build freecad-0.18.4-r1::waebbl
```/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lTKFillet
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lTKMesh
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lTKernel
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lTKG2d
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lTKG3d ```

**Comment by khumarahn** [comment] 2020-05-04 10:28
Uh, this seems to work:
```
diff --git a/media-gfx/freecad/freecad-0.18.4-r1.ebuild b/media-gfx/freecad/freecad-0.18.4-r1.ebuild
index 8e46089..d66cec5 100644
--- a/media-gfx/freecad/freecad-0.18.4-r1.ebuild
+++ b/media-gfx/freecad/freecad-0.18.4-r1.ebuild
@@ -169,7 +169,7 @@ src_prepare() {
 
 src_configure() {
        local occ_lib="lib"
-       if has_version "=sci-libs/opencascade-7.4.0:7.4.0"; then
+       if has_version "~sci-libs/opencascade-7.4.0:7.4.0"; then
                occ_lib=$(get_libdir)
        fi
```

**Comment by waebbl** [comment] 2020-05-04 10:33
@khumarahn This is a duplicate of issue #228

**Comment by khumarahn** [comment] 2020-05-04 10:38
yes!

**Comment by waebbl** [comment] 2020-12-21 16:22
I've added an oce USE flag to 0.18.5 and live ebuilds. Feel free to test those and report back any issues you encounter.

**Closed by waebbl** 2020-12-21 16:22 UTC
Labels: bug, enhancement
