### ISSUE TITLE
media-gfx/freecad-0.18.5 fails

### ISSUE THREAD

**Issue by chl-repo** [waebbl/waebbl-gentoo#271] opened 2020-12-09 19:25 UTC
Building freecad-0.18.5 failed for me several times during configuration, with the message 
"CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find Coin3D (missing: COIN3D_INCLUDE_DIRS)"

Applying freecad-0.18.4-0001-Fix-coin-related-variables-to-use-new-naming-from-4.0.0.patch solved the problem. 

Maybe this patch should also be included in the freecad-0.18.5 ebuild. 

Please let me know if you need further information or other help as e.g. testing. 

CHL

**Comment by waebbl** [comment] 2020-12-09 20:02
Hello @chl-repo, which version of coin do you have installed, and from which repo? I had a lot of builds during development due to some failures, but it never failed on coin.
Also could you please give a little more context, especially from which file(s) the failing cmake module has been called (often listed in the lines around the error message).

**Comment by chl-repo** [comment] 2020-12-09 21:26
I have coin-4.0.0 from your repo installed. 

For freecad, vtk and med python_single_target_python3_7 is set. 

Moreover, I attach the build.log.
[build.log.txt](https://github.com/waebbl/waebbl-gentoo/files/5668748/build.log.txt)

**Comment by waebbl** [comment] 2020-12-09 21:37
Thanks, the problem is probably the coin ebuild from my overlay. It's obsolete and the ::gentoo ebuild should be used instead. Guess, I need to remove the one from my overlay. Could you please try coin from ::gentoo and see if that works?

**Comment by chl-repo** [comment] 2020-12-10 06:53
Hi waebbl, 

coin::gentoo works. It has however the disadvantage that it does not work with latest cmake.

Many thanks for your swift reaction and support. 
CHL

**Comment by waebbl** [comment] 2020-12-10 07:12
Oh, I wasn't aware of this. My last build of coin was back in August.
If you like, you can check b.g.o for this issue and see if it was already reported or open a bug report there if not.

I'm closing this issue then. Feel free to re-open if the issue persists.

**Closed by waebbl** 2020-12-10 07:12 UTC

**Comment by chl-repo** [comment] 2020-12-22 19:49
Sorry, 

wenn ich mich erst jetzt und auf Deutsch melde, das ist aber weniger
kompiziert als den Issue in github nochmals aufzumachen. 

Das Problem mit coin und cmake scheint ein Bug von cmake zu sein, der
mit dem nächsten Release behoben wird. 

Ferner bin ich gerade beim Update mit Deinem
freecad-0.18.5-r1.ebuild auf ein kleines Problem gestoßen. Der
Menü-Eintrag verweist auf /usr/bin/FreeCAD es wird aber nur ein link zu 
/usr/bin/freecad angelegt, was bei mir unter KDE zu einer Fehlermeldung
führt. 

Ich habe daher unter src_install im ebuild noch folgendes
ergänzt:
 
dosym ../$(get_libdir)/${PN}/bin/FreeCAD /usr/bin/FreeCAD 

Beste Grüße aus München
Christoph Löhr

Am Wed, 09 Dec 2020 12:02:36 -0800
schrieb Bernd <notifications@github.com>:

> Hello @chl-repo, which version of coin do you have installed, and
> from which repo? I had a lot of builds during development due to some
> failures, but it never failed on coin. Also could you please give a
> little more context, especially from which file(s) the failing cmake
> module has been called (often listed in the lines around the error
> message).
>

**Comment by waebbl** [comment] 2020-12-22 21:36
Hallo Christoph,

danke fuer den Hinweis.
Das wird in KDE auch ueber die .desktop Dateien gesteuert oder? Hab hier
grad noch 0.18.5 installiert, das update auf 0.18.5-r1 ist noch in der
Queue. Ich schau mir das mal und schau ob ich da noch nen zusaetzlichen
Link einbaue oder die desktop Datei anpasse.

Viele Gruesse aus innerhalb der Stadt
Bernd


Am Di., 22. Dez. 2020 um 20:49 Uhr schrieb chl-repo <
notifications@github.com>:
