### ISSUE TITLE
dev-python/pivy-0.6.4 fails to compile

### ISSUE THREAD

**Issue by Bajdi** [waebbl/waebbl-gentoo#42] opened 2018-12-20 19:22 UTC
Hi, I'm trying to install Freecad via your overlay. But compiling pivy-0.6.4 fails.
```
`Warning: Pivy has only been tested with the following SWIG versions: 3.0.8 3.0.10.
calling: cmake 
checking for COIN via cmake
checking for SOQT via cmake
Traceback (most recent call last):
  File "setup.py", line 666, in <module>
    platforms=['Any']
  File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 588, in run
    self.pivy_configure()
  File "setup.py", line 453, in pivy_configure
    self.check_with_cmake()
  File "setup.py", line 229, in check_with_cmake
    if config_dict['SOQT_FOUND'] == 'false':
KeyError: 'SOQT_FOUND'
 * ERROR: dev-python/pivy-0.6.4::waebbl failed (compile phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line  124:  Called src_compile
 *   environment, line 2748:  Called distutils-r1_src_compile
 *   environment, line  959:  Called _distutils-r1_run_foreach_impl 'distutils-r1_python_compile'
 *   environment, line  478:  Called python_foreach_impl 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line 2301:  Called multibuild_foreach_variant '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line 1673:  Called _multibuild_run '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line 1671:  Called _python_multibuild_wrapper 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line  681:  Called distutils-r1_run_phase 'distutils-r1_python_compile'
 *   environment, line  950:  Called distutils-r1_python_compile
 *   environment, line  824:  Called esetup.py 'build' '-j' '6'
 *   environment, line 1218:  Called die
 * The specific snippet of code:
 *       "${@}" || die "${die_args[@]}";
 * 
 * If you need support, post the output of `emerge --info '=dev-python/pivy-0.6.4::waebbl'`,
 * the complete build log and the output of `emerge -pqv '=dev-python/pivy-0.6.4::waebbl'`.
 * The complete build log is located at '/var/tmp/portage/dev-python/pivy-0.6.4/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-python/pivy-0.6.4/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-python/pivy-0.6.4/work/pivy-0.6.4'
 * S: '/var/tmp/portage/dev-python/pivy-0.6.4/work/pivy-0.6.4'

>>> Failed to emerge dev-python/pivy-0.6.4, Log file:

>>>  '/var/tmp/portage/dev-python/pivy-0.6.4/temp/build.log'

 * Messages for package dev-python/pivy-0.6.4:

 * ERROR: dev-python/pivy-0.6.4::waebbl failed (compile phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line  124:  Called src_compile
 *   environment, line 2748:  Called distutils-r1_src_compile
 *   environment, line  959:  Called _distutils-r1_run_foreach_impl 'distutils-r1_python_compile'
 *   environment, line  478:  Called python_foreach_impl 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line 2301:  Called multibuild_foreach_variant '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line 1673:  Called _multibuild_run '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line 1671:  Called _python_multibuild_wrapper 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line  681:  Called distutils-r1_run_phase 'distutils-r1_python_compile'
 *   environment, line  950:  Called distutils-r1_python_compile
 *   environment, line  824:  Called esetup.py 'build' '-j' '6'
 *   environment, line 1218:  Called die
 * The specific snippet of code:
 *       "${@}" || die "${die_args[@]}";
 * 
 * If you need support, post the output of `emerge --info '=dev-python/pivy-0.6.4::waebbl'`,
 * the complete build log and the output of `emerge -pqv '=dev-python/pivy-0.6.4::waebbl'`.
 * The complete build log is located at '/var/tmp/portage/dev-python/pivy-0.6.4/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-python/pivy-0.6.4/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-python/pivy-0.6.4/work/pivy-0.6.4'
 * S: '/var/tmp/portage/dev-python/pivy-0.6.4/work/pivy-0.6.4`
```
media-libs/SoQt
      Latest version installed: 1.5.0-r1
media-libs/coin
      Latest version installed: 3.1.3-r2

I run a stable system (amd64) and recently updated my complete system. I used to run 0.15 and was trying to update to a higher version ...

**Comment by Bajdi** [comment] 2018-12-20 20:42
Tried compiling coin-4.0.0a but did not get far:
```
 * Work directory: /var/tmp/portage/media-libs/coin-4.0.0a_pre20180921/work/boost-header-libs-full global id: 25bb7785a024 (was 25bb778 branch: default
 * Cloning https://bitbucket.org/Coin3D/coin to /usr/portage/distfiles/hg-src/Coin3D/coin
applying clone bundle from https://api.media.atlassian.com/file/ca8ac694-8b46-45b5-affb-6bbba948b9cd/binary?client=64098d31-1676-4941-8a09-30b447252903&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOnsidXJuOmZpbGVzdG9yZTpmaWxlOmNhOGFjNjk0LThiNDYtNDViNS1hZmZiLTZiYmJhOTQ4YjljZCI6WyJyZWFkIl19LCJleHAiOjE1NDUzMzg1NzAsImlzcyI6IjY0MDk4ZDMxLTE2NzYtNDk0MS04YTA5LTMwYjQ0NzI1MjkwMyIsIm5iZiI6MTU0NTMzODE1MH0.scwPq8pxz5oCgl7KxbRU2J4VjtQsSHE2dAO3sch26UU
adding changesets
adding manifests
adding file changes                                                                                                                         
added 11707 changesets with 71756 changes to 6487 files (+1 heads)                                                                          
finished applying clone bundle
searching for changes
adding changesets
adding manifests                                                                                                                            
adding file changes
added 226 changesets with 1329 changes to 901 files
new changesets de2e5a9fee0a:acee8063042f
 * Creating working directory in /var/tmp/portage/media-libs/coin-4.0.0a_pre20180921/work/Coin-4.0.0a_pre20180921 (target revision: cf2a467)
updating to branch default
cloning subrepo build/general from /usr/portage/distfiles/hg-src/Coin3D/generalmsvcgeneration
abort: HTTP Error 404: Not Found
 * ERROR: media-libs/coin-4.0.0a_pre20180921::waebbl failed (unpack phase):
 *   hg clone failed
 * 
 * Call stack:
 *     ebuild.sh, line  124:  Called src_unpack
 *   environment, line 2941:  Called mercurial_fetch
 *   environment, line 2461:  Called die
 * The specific snippet of code:
 *       hg clone ${EHG_QUIET_CMD_OPT} --updaterev="${EHG_REVISION}" ${EHG_CONFIG:+--config ${EHG_CONFIG}} "${EHG_STORE_DIR}/${EHG_PROJECT}/${module}" "${sourcedir}" || die "hg clone failed";
```

**Comment by Bajdi** [comment] 2018-12-21 12:45
I was able to emerge coin-4.0.0a_pre20180416 from the official tree. I then emerged pivy-0.6.4 using the --nodeps option. I then tried to emerge freecad but got the following error:

```
es/FreeCADBase.dir/__/zipios++/fcoll.cpp.o CMakeFiles/FreeCADBase.dir/__/zipios++/fcollexceptions.cpp.o CMakeFiles/FreeCADBase.dir/__/zipios++/fileentry.cpp.o CMakeFiles/FreeCADBase.dir/__/zipios++/filepath.cpp.o CMakeFiles/FreeCADBase.dir/__/zipios++/filterinputstreambuf.cpp.o CMakeFiles/FreeCADBase.dir/__/zipios++/filteroutputstreambuf.cpp.o CMakeFiles/FreeCADBase.dir/__/zipios++/gzipoutputstream.cpp.o CMakeFiles/FreeCADBase.dir/__/zipios++/gzipoutputstreambuf.cpp.o CMakeFiles/FreeCADBase.dir/__/zipios++/inflateinputstreambuf.cpp.o CMakeFiles/FreeCADBase.dir/__/zipios++/zipfile.cpp.o CMakeFiles/FreeCADBase.dir/__/zipios++/ziphead.cpp.o CMakeFiles/FreeCADBase.dir/__/zipios++/zipheadio.cpp.o CMakeFiles/FreeCADBase.dir/__/zipios++/zipinputstream.cpp.o CMakeFiles/FreeCADBase.dir/__/zipios++/zipinputstreambuf.cpp.o CMakeFiles/FreeCADBase.dir/__/zipios++/zipoutputstreambuf.cpp.o CMakeFiles/FreeCADBase.dir/__/zipios++/zipoutputstream.cpp.o -lmpi_cxx -lmpi -lpython3.6m -lxerces-c -lboost_filesystem-mt -lboost_program_options-mt -lboost_regex-mt -lboost_system-mt -lboost_thread-mt -lboost_chrono-mt -lboost_date_time-mt -lboost_atomic-mt -lpthread -lz /usr/lib64/libQt5Core.so.5.11.1 -lutil -ldl 
make[2]: Leaving directory '/var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999_build'
[  6%] Built target FreeCADBase
make[1]: Leaving directory '/var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999_build'
make: *** [Makefile:130: all] Error 2
 * ERROR: media-gfx/freecad-9999::waebbl failed (compile phase):
 *   emake failed
```

**Comment by waebbl** [comment] 2018-12-22 18:39
@Bajdi There's no error message in your quote. Can you please post some more of the output?

**Comment by waebbl** [comment] 2018-12-22 19:00
@Bajdi Please try again, using my updated ebuild for coin, SoQt and pivy

**Comment by Bajdi** [comment] 2018-12-22 20:18
Updated the overlay and recompiled coin, SoQT and pivy. But still can't compile Freecad :(
```
[  5%] Building CXX object src/Base/CMakeFiles/FreeCADBase.dir/__/zipios++/ziphead.cpp.o
cd /var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999_build/src/Base && /usr/x86_64-pc-linux-gnu/gcc-bin/6.4.0/x86_64-pc-linux-gnu-g++ -DFreeCADBase_EXPORTS -DHAVE_CONFIG_H -DHAVE_SWIG=1 -DQT_CORE_LIB -DQT_NO_DEBUG -D_OCC64 -I/var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999_build -I/var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999_build/src -I/var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999/src -I/var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999_build/src/Base -I/var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999/src/Base -I/usr/include/python3.6m -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++   -Wall -Wextra -Wno-write-strings -march=native -O2 -pipe -std=c++11 -D_OCC64 -fPIC   -pthread -fPIC -std=gnu++11 -o CMakeFiles/FreeCADBase.dir/__/zipios++/ziphead.cpp.o -c /var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999/src/zipios++/ziphead.cpp
[  5%] Building CXX object src/Base/CMakeFiles/FreeCADBase.dir/__/zipios++/zipheadio.cpp.o
cd /var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999_build/src/Base && /usr/x86_64-pc-linux-gnu/gcc-bin/6.4.0/x86_64-pc-linux-gnu-g++ -DFreeCADBase_EXPORTS -DHAVE_CONFIG_H -DHAVE_SWIG=1 -DQT_CORE_LIB -DQT_NO_DEBUG -D_OCC64 -I/var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999_build -I/var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999_build/src -I/var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999/src -I/var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999_build/src/Base -I/var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999/src/Base -I/usr/include/python3.6m -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++   -Wall -Wextra -Wno-write-strings -march=native -O2 -pipe -std=c++11 -D_OCC64 -fPIC   -pthread -fPIC -std=gnu++11 -o CMakeFiles/FreeCADBase.dir/__/zipios++/zipheadio.cpp.o -c /var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999/src/zipios++/zipheadio.cpp
[  5%] Building CXX object src/Base/CMakeFiles/FreeCADBase.dir/__/zipios++/zipinputstream.cpp.o
cd /var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999_build/src/Base && /usr/x86_64-pc-linux-gnu/gcc-bin/6.4.0/x86_64-pc-linux-gnu-g++ -DFreeCADBase_EXPORTS -DHAVE_CONFIG_H -DHAVE_SWIG=1 -DQT_CORE_LIB -DQT_NO_DEBUG -D_OCC64 -I/var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999_build -I/var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999_build/src -I/var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999/src -I/var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999_build/src/Base -I/var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999/src/Base -I/usr/include/python3.6m -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++   -Wall -Wextra -Wno-write-strings -march=native -O2 -pipe -std=c++11 -D_OCC64 -fPIC   -pthread -fPIC -std=gnu++11 -o CMakeFiles/FreeCADBase.dir/__/zipios++/zipinputstream.cpp.o -c /var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999/src/zipios++/zipinputstream.cpp
[  5%] Building CXX object src/Base/CMakeFiles/FreeCADBase.dir/__/zipios++/zipinputstreambuf.cpp.o
cd /var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999_build/src/Base && /usr/x86_64-pc-linux-gnu/gcc-bin/6.4.0/x86_64-pc-linux-gnu-g++ -DFreeCADBase_EXPORTS -DHAVE_CONFIG_H -DHAVE_SWIG=1 -DQT_CORE_LIB -DQT_NO_DEBUG -D_OCC64 -I/var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999_build -I/var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999_build/src -I/var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999/src -I/var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999_build/src/Base -I/var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999/src/Base -I/usr/include/python3.6m -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++   -Wall -Wextra -Wno-write-strings -march=native -O2 -pipe -std=c++11 -D_OCC64 -fPIC   -pthread -fPIC -std=gnu++11 -o CMakeFiles/FreeCADBase.dir/__/zipios++/zipinputstreambuf.cpp.o -c /var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999/src/zipios++/zipinputstreambuf.cpp
[  5%] Building CXX object src/Base/CMakeFiles/FreeCADBase.dir/__/zipios++/zipoutputstreambuf.cpp.o
cd /var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999_build/src/Base && /usr/x86_64-pc-linux-gnu/gcc-bin/6.4.0/x86_64-pc-linux-gnu-g++ -DFreeCADBase_EXPORTS -DHAVE_CONFIG_H -DHAVE_SWIG=1 -DQT_CORE_LIB -DQT_NO_DEBUG -D_OCC64 -I/var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999_build -I/var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999_build/src -I/var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999/src -I/var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999_build/src/Base -I/var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999/src/Base -I/usr/include/python3.6m -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++   -Wall -Wextra -Wno-write-strings -march=native -O2 -pipe -std=c++11 -D_OCC64 -fPIC   -pthread -fPIC -std=gnu++11 -o CMakeFiles/FreeCADBase.dir/__/zipios++/zipoutputstreambuf.cpp.o -c /var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999/src/zipios++/zipoutputstreambuf.cpp
[  5%] Building CXX object src/Base/CMakeFiles/FreeCADBase.dir/__/zipios++/zipoutputstream.cpp.o
cd /var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999_build/src/Base && /usr/x86_64-pc-linux-gnu/gcc-bin/6.4.0/x86_64-pc-linux-gnu-g++ -DFreeCADBase_EXPORTS -DHAVE_CONFIG_H -DHAVE_SWIG=1 -DQT_CORE_LIB -DQT_NO_DEBUG -D_OCC64 -I/var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999_build -I/var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999_build/src -I/var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999/src -I/var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999_build/src/Base -I/var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999/src/Base -I/usr/include/python3.6m -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++   -Wall -Wextra -Wno-write-strings -march=native -O2 -pipe -std=c++11 -D_OCC64 -fPIC   -pthread -fPIC -std=gnu++11 -o CMakeFiles/FreeCADBase.dir/__/zipios++/zipoutputstream.cpp.o -c /var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999/src/zipios++/zipoutputstream.cpp
[  5%] Linking CXX shared library ../../lib/libFreeCADBase.so
cd /var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999_build/src/Base && /usr/bin/cmake -E cmake_link_script CMakeFiles/FreeCADBase.dir/link.txt --verbose=1
/usr/x86_64-pc-linux-gnu/gcc-bin/6.4.0/x86_64-pc-linux-gnu-g++ -fPIC -Wall -Wextra -Wno-write-strings -march=native -O2 -pipe -std=c++11 -D_OCC64 -Wl,-O1 -Wl,--as-needed -Wl,--no-undefined -shared -Wl,-soname,libFreeCADBase.so -o ../../lib/libFreeCADBase.so CMakeFiles/FreeCADBase.dir/__/CXX/cxxextensions.c.o CMakeFiles/FreeCADBase.dir/__/CXX/cxx_extensions.cxx.o CMakeFiles/FreeCADBase.dir/__/CXX/cxxsupport.cxx.o CMakeFiles/FreeCADBase.dir/__/CXX/IndirectPythonInterface.cxx.o CMakeFiles/FreeCADBase.dir/Axis.cpp.o CMakeFiles/FreeCADBase.dir/AxisPyImp.cpp.o CMakeFiles/FreeCADBase.dir/Base64.cpp.o CMakeFiles/FreeCADBase.dir/BaseClass.cpp.o CMakeFiles/FreeCADBase.dir/BaseClassPyImp.cpp.o CMakeFiles/FreeCADBase.dir/BoundBoxPyImp.cpp.o CMakeFiles/FreeCADBase.dir/Builder3D.cpp.o CMakeFiles/FreeCADBase.dir/Console.cpp.o CMakeFiles/FreeCADBase.dir/CoordinateSystem.cpp.o CMakeFiles/FreeCADBase.dir/CoordinateSystemPyImp.cpp.o CMakeFiles/FreeCADBase.dir/Debugger.cpp.o CMakeFiles/FreeCADBase.dir/Exception.cpp.o CMakeFiles/FreeCADBase.dir/ExceptionFactory.cpp.o CMakeFiles/FreeCADBase.dir/Factory.cpp.o CMakeFiles/FreeCADBase.dir/FileInfo.cpp.o CMakeFiles/FreeCADBase.dir/FileTemplate.cpp.o CMakeFiles/FreeCADBase.dir/FutureWatcherProgress.cpp.o CMakeFiles/FreeCADBase.dir/gzstream.cpp.o CMakeFiles/FreeCADBase.dir/GeometryPyCXX.cpp.o CMakeFiles/FreeCADBase.dir/Handle.cpp.o CMakeFiles/FreeCADBase.dir/InputSource.cpp.o CMakeFiles/FreeCADBase.dir/Interpreter.cpp.o CMakeFiles/FreeCADBase.dir/Matrix.cpp.o CMakeFiles/FreeCADBase.dir/MatrixPyImp.cpp.o CMakeFiles/FreeCADBase.dir/MemDebug.cpp.o CMakeFiles/FreeCADBase.dir/Parameter.cpp.o CMakeFiles/FreeCADBase.dir/ParameterPy.cpp.o CMakeFiles/FreeCADBase.dir/Persistence.cpp.o CMakeFiles/FreeCADBase.dir/PersistencePyImp.cpp.o CMakeFiles/FreeCADBase.dir/Placement.cpp.o CMakeFiles/FreeCADBase.dir/PlacementPyImp.cpp.o CMakeFiles/FreeCADBase.dir/PyExport.cpp.o CMakeFiles/FreeCADBase.dir/PyObjectBase.cpp.o CMakeFiles/FreeCADBase.dir/Reader.cpp.o CMakeFiles/FreeCADBase.dir/Rotation.cpp.o CMakeFiles/FreeCADBase.dir/RotationPyImp.cpp.o CMakeFiles/FreeCADBase.dir/Sequencer.cpp.o CMakeFiles/FreeCADBase.dir/Stream.cpp.o CMakeFiles/FreeCADBase.dir/Swap.cpp.o CMakeFiles/FreeCADBase.dir/swigpyrun.cpp.o CMakeFiles/FreeCADBase.dir/TimeInfo.cpp.o CMakeFiles/FreeCADBase.dir/Tools.cpp.o CMakeFiles/FreeCADBase.dir/Tools2D.cpp.o CMakeFiles/FreeCADBase.dir/Translate.cpp.o CMakeFiles/FreeCADBase.dir/Type.cpp.o CMakeFiles/FreeCADBase.dir/Uuid.cpp.o CMakeFiles/FreeCADBase.dir/Vector3D.cpp.o CMakeFiles/FreeCADBase.dir/VectorPyImp.cpp.o CMakeFiles/FreeCADBase.dir/ViewProj.cpp.o CMakeFiles/FreeCADBase.dir/Writer.cpp.o CMakeFiles/FreeCADBase.dir/XMLTools.cpp.o CMakeFiles/FreeCADBase.dir/UnitsApi.cpp.o CMakeFiles/FreeCADBase.dir/UnitsApiPy.cpp.o CMakeFiles/FreeCADBase.dir/UnitsSchema.cpp.o CMakeFiles/FreeCADBase.dir/UnitsSchemaInternal.cpp.o CMakeFiles/FreeCADBase.dir/UnitsSchemaMKS.cpp.o CMakeFiles/FreeCADBase.dir/UnitsSchemaImperial1.cpp.o CMakeFiles/FreeCADBase.dir/UnitsSchemaCentimeters.cpp.o CMakeFiles/FreeCADBase.dir/UnitsSchemaMmMin.cpp.o CMakeFiles/FreeCADBase.dir/Quantity.cpp.o CMakeFiles/FreeCADBase.dir/QuantityPyImp.cpp.o CMakeFiles/FreeCADBase.dir/Unit.cpp.o CMakeFiles/FreeCADBase.dir/UnitPyImp.cpp.o CMakeFiles/FreeCADBase.dir/PyTools.c.o CMakeFiles/FreeCADBase.dir/PreCompiled.cpp.o CMakeFiles/FreeCADBase.dir/__/zipios++/basicentry.cpp.o CMakeFiles/FreeCADBase.dir/__/zipios++/collcoll.cpp.o CMakeFiles/FreeCADBase.dir/__/zipios++/deflateoutputstreambuf.cpp.o CMakeFiles/FreeCADBase.dir/__/zipios++/dircoll.cpp.o CMakeFiles/FreeCADBase.dir/__/zipios++/directory.cpp.o CMakeFiles/FreeCADBase.dir/__/zipios++/fcoll.cpp.o CMakeFiles/FreeCADBase.dir/__/zipios++/fcollexceptions.cpp.o CMakeFiles/FreeCADBase.dir/__/zipios++/fileentry.cpp.o CMakeFiles/FreeCADBase.dir/__/zipios++/filepath.cpp.o CMakeFiles/FreeCADBase.dir/__/zipios++/filterinputstreambuf.cpp.o CMakeFiles/FreeCADBase.dir/__/zipios++/filteroutputstreambuf.cpp.o CMakeFiles/FreeCADBase.dir/__/zipios++/gzipoutputstream.cpp.o CMakeFiles/FreeCADBase.dir/__/zipios++/gzipoutputstreambuf.cpp.o CMakeFiles/FreeCADBase.dir/__/zipios++/inflateinputstreambuf.cpp.o CMakeFiles/FreeCADBase.dir/__/zipios++/zipfile.cpp.o CMakeFiles/FreeCADBase.dir/__/zipios++/ziphead.cpp.o CMakeFiles/FreeCADBase.dir/__/zipios++/zipheadio.cpp.o CMakeFiles/FreeCADBase.dir/__/zipios++/zipinputstream.cpp.o CMakeFiles/FreeCADBase.dir/__/zipios++/zipinputstreambuf.cpp.o CMakeFiles/FreeCADBase.dir/__/zipios++/zipoutputstreambuf.cpp.o CMakeFiles/FreeCADBase.dir/__/zipios++/zipoutputstream.cpp.o -lmpi_cxx -lmpi -lpython3.6m -lxerces-c -lboost_filesystem-mt -lboost_program_options-mt -lboost_regex-mt -lboost_system-mt -lboost_thread-mt -lboost_chrono-mt -lboost_date_time-mt -lboost_atomic-mt -lpthread -lz /usr/lib64/libQt5Core.so.5.11.1 -lutil -ldl 
make[2]: Leaving directory '/var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999_build'
[  6%] Built target FreeCADBase
make[1]: Leaving directory '/var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999_build'
make: *** [Makefile:130: all] Error 2
 * ERROR: media-gfx/freecad-9999::waebbl failed (compile phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=media-gfx/freecad-9999::waebbl'`,
 * the complete build log and the output of `emerge -pqv '=media-gfx/freecad-9999::waebbl'`.
 * The complete build log is located at '/var/tmp/portage/media-gfx/freecad-9999/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/media-gfx/freecad-9999/temp/environment'.
 * Working directory: '/var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999_build'
 * S: '/var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999'

>>> Failed to emerge media-gfx/freecad-9999, Log file:

>>>  '/var/tmp/portage/media-gfx/freecad-9999/temp/build.log'

 * Messages for package media-gfx/freecad-9999:

 * ERROR: media-gfx/freecad-9999::waebbl failed (compile phase):
 *   emake failed
```

**Comment by Bajdi** [comment] 2018-12-23 10:15
Ah, I was using vtk-7 from the official tree. Switched to vtk-8 from your overlay and now I was able to successfully compile Freecad :) 
Thanks for the help and the ebuild :)

**Comment by kamikaze** [comment] 2019-01-24 20:08
got the same issue... is there any way to make vtk-8 installable automagically as a dependency?

**Comment by kamikaze** [comment] 2019-01-24 20:09
also I have `sci-libs/vtk-8.1.1::waebbl` installed... so issue is not solved for my case.

**Comment by kamikaze** [comment] 2019-01-24 20:11
oh... there is no SoQt installed. Any way to get this package as a dependency? Would be nice to not install it manually...

**Comment by kamikaze** [comment] 2019-01-24 20:12
`
Platform...linux
Python version...3.6.6
Checking for swig...
'/usr/bin/swig'
Checking for SWIG version...
3.0.12
Warning: Pivy has only been tested with the following SWIG versions: 3.0.8 3.0.10.
calling: cmake 

checking for COIN via cmake

checking for SOQT via cmake
Traceback (most recent call last):
  File "setup.py", line 666, in <module>
    platforms=['Any']
  File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 588, in run
    self.pivy_configure()
  File "setup.py", line 453, in pivy_configure
    self.check_with_cmake()
  File "setup.py", line 229, in check_with_cmake
    if config_dict['SOQT_FOUND'] == 'false':
KeyError: 'SOQT_FOUND'
`

**Comment by waebbl** [comment] 2019-01-28 17:40
@kamikaze I'm not able to reproduce the issue you get. Could you please post the output of `emerge -pv vtk coin SoQt opencascade pivy`?

> got the same issue... is there any way to make vtk-8 installable automagically as a dependency?

`=sci-libs/opencascade-7.3.0::waebbl` depends on `>=sci-libs/vtk-8.1.0`. Maybe the problem is about 8.1.0 vs. 8.1.1 although you're saying you have 8.1.1 installed already.

> oh... there is no SoQt installed. Any way to get this package as a dependency? Would be nice to not install it manually...

`pivy` pulls in `>=coin-4.0.0a_pre2018121` and `>=SoQt-1.6.0a_pre20181221`. Is it possible you're using an outdated sync of my overlay?

**Comment by kamikaze** [comment] 2019-01-28 17:46
```
[ebuild   R    ] media-libs/coin-4.0.0a_pre20181221::waebbl  USE="3ds-import draggers javascript manipulators nodekits openal simage threads vrml97 -debug -doc -exceptions -qthelp -static-libs -test" 0 KiB
[ebuild   R    ] sci-libs/vtk-8.1.1::waebbl  USE="X ffmpeg imaging mpi postgres python qt5 rendering tbb theora -R -all-modules (-aqua) -boost -doc (-examples) -gdal -java -json -kaapi -mysql -odbc -offscreen -tcl -test -tk -views -web -xdmf2" PYTHON_TARGETS="python3_6" VIDEO_CARDS="nvidia" 0 KiB
[ebuild   R    ] media-libs/SoQt-1.6.0a_pre20181221::waebbl  USE="coin-iv-extensions -doc -qthelp -spacenav" 0 KiB
[ebuild   R    ] sci-libs/opencascade-7.3.0:7.3.0::waebbl  USE="ffmpeg qt5 vtk -debug -doc -examples -freeimage -gl2ps -gles2 -inspector -java -optimize -tbb -test" 47 439 KiB
[ebuild  N     ] dev-python/pivy-0.6.4::waebbl  PYTHON_TARGETS="python3_6" 0 KiB
```

**Comment by kamikaze** [comment] 2019-02-10 04:25
still getting same error. anything I can assist with?

**Comment by qinq-net** [comment] 2019-04-10 03:22
It seems that removing the `NONE` in line 1 of `CMakeLists.txt` allows it to configure.

**Comment by alexxy** [comment] 2019-04-10 16:24
> It seems that removing the `NONE` in line 1 of `CMakeLists.txt` allows it to configure.
> It builds with a user patch.
> 
> ```diff
> --- pivy-0.6.4.old/CMakeLists.txt       2018-06-08 16:15:18.000000000 +0800
> +++ pivy-0.6.4/CMakeLists.txt   2019-04-10 11:15:17.947823788 +0800
> @@ -1,4 +1,4 @@
> -project(pivy_cmake_setup NONE)
> +project(pivy_cmake_setup)
>  cmake_minimum_required(VERSION 3.5)
> ```

That works also for me.

**Comment by zwim** [comment] 2019-06-12 13:27
> It seems that removing the `NONE` in line 1 of `CMakeLists.txt` allows it to configure.
> It builds with a user patch.
> 
> ```diff
> --- pivy-0.6.4.old/CMakeLists.txt       2018-06-08 16:15:18.000000000 +0800
> +++ pivy-0.6.4/CMakeLists.txt   2019-04-10 11:15:17.947823788 +0800
> @@ -1,4 +1,4 @@
> -project(pivy_cmake_setup NONE)
> +project(pivy_cmake_setup)
>  cmake_minimum_required(VERSION 3.5)
> ```

It works for me, too. 
Just copy the patch to /etc/portage/patches/dev-python/pivy-0.6.4/compile.patch

**Comment by waebbl** [comment] 2019-06-12 20:29
Thanks @qinq-net this seems to solve the issue. The patch will be in one of the next updates.

**Closed** 2019-06-14 14:31 UTC
Labels: bug
